### ISSUE TITLE
A bug in 'RandomFlip3D'

### ISSUE THREAD

**Issue by wangbo-zhao** [XuyangBai/TransFusion#1]
I keep all environments as the same as you. mmdet==2.10.0, mmcv==1.2.4, and I adopt the config file named "transfusion_waymo_voxel_LC.py"

If we get true in "results['flip']", then "mmcv.imflip(results[key], direction=results['flip_direction'])" will generate a np<class 'numpy.ndarray'> instead of a <class 'list'>, 
![image](https://user-images.githubusercontent.com/56866854/164141148-c627634a-710a-4c28-9a2d-8032acd124e1.png)

This will result a bug in 
![image](https://user-images.githubusercontent.com/56866854/164141417-931ac905-4298-4446-851b-c8bb24f246ee.png)

**Comment by XuyangBai** [comment]
Hi, sorry for the late reply. Yes, I forget to turn the multiple images into a list, I will fix this bug soon. You can use this solution first. https://github.com/XuyangBai/TransFusion/issues/5

**Comment by XuyangBai** [comment]
Solved in https://github.com/XuyangBai/TransFusion/commit/ebd8ba4716bfbf324efc5164f53f9e9b8778556c, sorry for the inconvience.
