### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by 13331549708** [XuyangBai/TransFusion#100]
python setup.python develop
Error reported during compilation
Error content：1 error detected in the compilation of "mmdet3d/ops/voxel/src/scatter_points_cuda.cu".
error: command '/usr/local/cuda-11.3/bin/nvcc' failed with exit status 1

**Comment by Rennylex** [comment]
Hi did you solve the problem? May I ask the version for each package you are using, thanks!

**Comment by MSunDYY** [comment]
replace line 272 in ops/voxel/src/scatter_points_cuda.cu with coors_map.index_put_({coors_id_argsort}, coors_map_sorted);
