### ISSUE TITLE
The performance of transfusion_nusc_voxel_LC 

### ISSUE THREAD

**Issue by Wang-pengfei** [XuyangBai/TransFusion#105]
Hi, Xuyang.

I'm currently working on reproducing TransFusion. After training for 20 epochs on LiDAR, I obtained results with mAP: 0.6463 and NDS: 0.6979, which are close to the original TransFusion-L.

However, when I continued training for 6 epochs for fusion, the first epoch yielded very low results with mAP: 0.3156 and NDS: 0.2860. Is this normal?

**Comment by Shiming94** [comment]
Hi, @Wang-pengfei , did you solve this problem? I trained Transfusion_L with the original script, but my performance can only reach NDS around 67 and mAP around 60. Do you have any ideas on how I can improve this, or are there any other tricks I missed?
