### ISSUE TITLE
KITTI Dataset

### ISSUE THREAD

**Issue by leeaccy** [XuyangBai/TransFusion#43]
Could you provide a KITTI formatted version? I want to train on my own KITTI dataset.

**Comment by ZhaoJiangJie** [comment]
My data only has forward radar scan data, similiar with kitti dataset,so there is a big difference between point range and waymo, especially in the dimension of the x-axis, how should this be modified?

**Comment by ChristopheZhao** [comment]
My data is also close to KITTI's data format.

**Comment by Galaxy-ZRX** [comment]
Hi, have you got any solutions with KITTI?

**Comment by XuyangBai** [comment]
Sorry, I do not have enough time to support KITTI. Feel free to post your config and training log if you met some problems on KITTI and I will help take a look.
