### ISSUE TITLE
Nighttime/Daytime

### ISSUE THREAD

**Issue by zwei-lin** [XuyangBai/TransFusion#46]
Hi,
  Thanks for the great work! Transfusion shows strong robustness of inferior image conditions. I want to reimplement the result for robustness test. However, I do not find the Nighttime/Daytime split for nuScenes on its web. Can you provide the validation split of nuScenes for Nighttime/Daytime?

**Comment by XuyangBai** [comment]
Hi, I changed the filter strategy in the nuscenes toolkit to only evaluate on Nighttime scenes or daytime scenes based on the description of each scene.  Specifically, you need to change the `load_gt` and `load_prediction` functions in the following file:

https://github.com/nutonomy/nuscenes-devkit/blob/28765b8477dbd3331bacd922fada867c2c4db1d7/python-sdk/nuscenes/eval/detection/evaluate.py
