### ISSUE TITLE
Error: subprocess-exited-with-error during setup.py develop for mmdet3d

### ISSUE THREAD

**Issue by ytan101** [XuyangBai/TransFusion#47]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
Whenever I run pip install -e . in the repo, I get error: subprocess-exited-with-error.
I am using CUDA 10.1
```
Installing collected packages: mmdet3d
  Running setup.py develop for mmdet3d
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [7 lines of output]
        running develop
        running egg_info
        /opt/conda/envs/mmdet_38/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        /opt/conda/envs/mmdet_38/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        error: [Errno 13] Permission denied
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [7 lines of output]
    running develop
    running egg_info
    /opt/conda/envs/mmdet_38/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    /opt/conda/envs/mmdet_38/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    error: [Errno 13] Permission denied
    [end of output]
```

**Reproduction**
1. What command or script did you run?
```
pip install -e .
```
**Environment**

1. Please run `python mmdet3d/utils/collect_env.py` to collect necessary environment infomation and paste it here.
Unable to run as I cannot install the repo

3. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - conda install pytorch==1.6.0 torchvision==0.7.0 cudatoolkit=10.1 -c pytorch
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by ytan101** [comment]
This was an issue with my ubuntu permissions. I had cloned the TransFusion repo with root user and attempted to install it with another user leading to conflicts with the permissions. To solve this, I deleted the repo and cloned it again (with my own user this time).

**Comment by pupu-chenyanyan** [comment]
Hi，I also encounter the problem when i run pip install -v -e . in transfusion fold. Can you give me some guidance? Thanks！
![Uploading Screenshot from 2023-11-12 16-49-07.png…]()
![Uploading Screenshot from 2023-11-12 16-53-12.png…]()
@ytan101 @XuyangBai

**Comment by pupu-chenyanyan** [comment]
Hi，I also encounter the problem when i run pip install -v -e . in transfusion fold. Can you give me some guidance? Thanks！
![Screenshot from 2023-11-12 16-49-07](https://github.com/XuyangBai/TransFusion/assets/73777333/763d1bf6-73bb-4ff6-b7ce-8e9cab746f6a)
![Screenshot from 2023-11-12 16-53-12](https://github.com/XuyangBai/TransFusion/assets/73777333/97b858f0-bb82-491d-bd2e-94523d1478a5)
 @ytan101 @XuyangBai

**Comment by lixingsky** [comment]
> Hi，I also encounter the problem when i run pip install -v -e . in transfusion fold. Can you give me some guidance? Thanks！ ![Screenshot from 2023-11-12 16-49-07](https://github.com/XuyangBai/TransFusion/assets/73777333/763d1bf6-73bb-4ff6-b7ce-8e9cab746f6a) ![Screenshot from 2023-11-12 16-53-12](https://github.com/XuyangBai/TransFusion/assets/73777333/97b858f0-bb82-491d-bd2e-94523d1478a5) [@ytan101](https://github.com/ytan101) [@XuyangBai](https://github.com/XuyangBai)



> 嗨，我在运行 pip install -v -e 时也遇到了问题。在输血褶皱中。您能给我一些指导吗？谢谢！ ![Screenshot from 2023-11-12 16-49-07](https://github.com/XuyangBai/TransFusion/assets/73777333/763d1bf6-73bb-4ff6-b7ce-8e9cab746f6a) ![Screenshot from 2023-11-12 16-53-12](https://github.com/XuyangBai/TransFusion/assets/73777333/97b858f0-bb82-491d-bd2e-94523d1478a5)

"The same error, resolved?"
