### ISSUE TITLE
question about the version of Waymo Datase

### ISSUE THREAD

**Issue by seonhoon1002** [XuyangBai/TransFusion#53]
Thank you for sharing your great work.

I have a question about Waymo Dataset

Table 2 in your paper, It was measured by Waymo dataset. But I wonder what is the version you used.

Summary:
what did you use version of Waymo?

**Comment by XuyangBai** [comment]
Hi, I use `v1.2`

**Comment by seonhoon1002** [comment]
There are some weird points, because performances of PVRCNN and LiDAR RCNN in table 2 are too low.

Bellow are performance measured by v1.2 in SST[1] and PV-RCNN++[2] 
Vehicle(reported in SST)
![image](https://user-images.githubusercontent.com/41002216/185773110-c4bd06f2-99f6-4dd1-b3f1-d29ce55729e3.png)
Pedestrian(reported in SST)
![image](https://user-images.githubusercontent.com/41002216/185773173-0e344f31-1892-47c7-b92d-5be6b01a24e3.png)
(reported in PV-RCNN++)
![image](https://user-images.githubusercontent.com/41002216/185773167-746b77eb-02d2-4b44-bec7-33ef1420b6a6.png)



reference
[1] Lue Fan, Ziqi Pang, Tianyuan Zhang, Yu-Xiong Wang, Hang Zhao, Feng Wang, Naiyan Wang, Zhaoxiang Zhang; Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR), 2022, pp. 8458-8468
[2] Shi, Shaoshuai, et al. "PV-RCNN++: Point-voxel feature set abstraction with local vector representation for 3D object detection." arXiv preprint arXiv:2102.00463 (2021)

**Comment by XuyangBai** [comment]
The results of PVRCNN are borrowed from CenterPoint, and the results of LiDAR-RCNN are taken from the LiDAR-RCNN paper

<img width="568" alt="截屏2022-08-21 12 14 09" src="https://user-images.githubusercontent.com/15166089/185775225-32d762d1-2d0f-4c96-a3e2-7666534f372b.png">


<img width="1106" alt="截屏2022-08-21 12 12 42" src="https://user-images.githubusercontent.com/15166089/185775219-a3fe6d12-8fed-44ba-8158-56603764ebfa.png">

The table here is the results for multi-class detection while the ones you provide is one model trained on one specific class (I assume) ?

**Comment by seonhoon1002** [comment]
Q1: The table here is the results for multi-class detection while the ones you provide is one model trained on one specific class (I assume) ?

A1: Vehcle in SST, yes you're right(but pedestrain trained on multi-class), I shouldn't bring vehicle result in SST. I think LiDAR-RCNN result is reasonable.

But in PV-RCNN case, I think there is a problem in Centerpoint. Because they report Waymo V1.0 result not V1.2(V1.0 is lower than v1.2). Please refer bellow table(refer from PV-RCNN original paper[1])

![image](https://user-images.githubusercontent.com/41002216/185776825-13922ad1-0031-455e-90b5-0e47e9b29355.png)

I think It is easily confused if not informed version of Waymo in paper. 

I think you should edit pv-rcnn result if you can.

reference
[1] Shaoshuai Shi, Chaoxu Guo, Li Jiang, Zhe Wang, Jianping Shi, Xiaogang Wang, and Hongsheng Li. PV-RCNN: Point-voxel feature set abstraction for 3D object detection. CVPR, 2020. 1

**Comment by XuyangBai** [comment]
Oh thanks for pointing out this information which I did not notice before, I will edit this result if I plan to have a new version.
