### ISSUE TITLE
a little bug for transfusion_head.py, but it does not affect the training results. 

### ISSUE THREAD

**Issue by xpyqiubai** [XuyangBai/TransFusion#54]
Many thanks to the authors for open sourcing the TransFusion code. I noticed that in line 827 of the "https://github.com/XuyangBai/TransFusion/blob/master/mmdet3d/models/dense_heads/transfusion_head.py" file, the author has mistakenly written self.img_feat_collapsed_pos as self.img_feat_collapsed_po due to an oversight. But it does not affect the training results, because it is equivalent to recalculating img_feat_collapsed_pos each time.

**Comment by XuyangBai** [comment]
Thanks! I will fix it
