### ISSUE TITLE
Read me

### ISSUE THREAD

**Issue by zhangzirui1998** [XuyangBai/TransFusion#55]
Could you write a read me  to teach us how to use the project? thanks a lot

**Comment by ChristopheZhao** [comment]
you can use this command to train or test same as mmdetection3d:
train: 
       `python tools/train.py configs/transfusion_nusc_voxel_L.py --work-dir results_dir/transfusion --gpu-id 0` 
test: 
       `python tools/test.py configs/transfusion_nusc_voxel_L.py results_dir/transfusion_nusc_voxel_L/epoch_7.pth --eval bbox --out results_dir/sassd/visualization/res_pkl_dir/res_transfusion_nusc_voxel_L.pkl` 
and you can visit mmdetction3d project for more details.

**Comment by zhangzirui1998** [comment]
Thank you for your advice！！！
