### ISSUE TITLE
How can I build this on RTX 3090?

### ISSUE THREAD

**Issue by sullicsullic** [XuyangBai/TransFusion#63]
I tried CUDA11.0, 11.3 but failed;
then I tried CUDA10.1, 10.2 with command <export TORCH_CUDA_ARCH_LIST="7.5"> but failed as well.

Please provide me the exact version information if you successfully build this on 30' GPU.
Thank you very much.

**Comment by zhangzirui1998** [comment]
30x GPU only adapt >>CUDA11.0

**Comment by lymcs** [comment]
It really cannot be reproduced on RTX3090？？

**Comment by sullicsullic** [comment]
solved

**Comment by Huleyun** [comment]
> solved

hello, I am trying to reproduce this in 3090, is there any advice?

**Comment by sullicsullic** [comment]
if u want to train, 8 3090s are needed in order not to slow down the training speed.
And 24g vram can only use a small backbone.
A100s are much better choice.
