### ISSUE TITLE
Build for CUDA verison > 11

### ISSUE THREAD

**Issue by Dhagash4** [XuyangBai/TransFusion#69]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
I am trying to build this repo, the steps I follow are:
1. Installing pytorch 1.10.1 with cuda113 
2. Installing mmcv-full with pytorch dependencies
3. Installing mmdet with pip
4. Then running pip install -v -e . from the respective folder

The error is either scatter_cuda_ is failing during compilation or if I use older version of cuda there is version mismatch that is happening. Can someone please tell how to build this repo, clearly the instrustions for installation are not helping and may require modification.

**Environment**

1. Please run `python mmdet3d/utils/collect_env.py` to collect necessary environment infomation and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - I used conda to install pytorch
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by Rennylex** [comment]
Hi! Can you tell me how you solved this problem?
