### ISSUE TITLE
Wrong link to data_preparation.md in README.md

### ISSUE THREAD

**Issue by cindyasucu** [XuyangBai/TransFusion#9]
In the https://github.com/XuyangBai/TransFusion/blob/master/README.md, at the section of https://github.com/XuyangBai/TransFusion#use-transfusion-->Benchmark Evaluation and Training, the link pointed to by getting_started.md is wrong, right now it points to the README.md itself, shall it point to https://github.com/XuyangBai/TransFusion/blob/master/docs/data_preparation.md?

**Comment by XuyangBai** [comment]
Thanks a lot, I have fixed it.
