### ISSUE TITLE
How can the results be visualised on the images and in BEV?

### ISSUE THREAD

**Issue by wqueree** [XuyangBai/TransFusion#91]

**Comment by Windy2001** [comment]
Hi, i ran into the same problem with you. Have you got any idea? 😊

**Comment by wqueree** [comment]
@Windy2001 I have found [this tutorial](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/tutorials/nuscenes_tutorial.ipynb) from nuscenes helpful. I hope you do too.

**Comment by wqueree** [comment]
BEV visualisation can be generated using [this script](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/eval/detection/evaluate.py) from the nuScenes developer kit.
